### ISSUE TITLE
main 의 테스트 컴파일이 깨져 CI 가 실패한다

### ISSUE THREAD

**Issue by dev-yunseong** [dev-yunseong/personal-website#192]
## Problem

`main` 의 CI 가 `:compileTestJava` 에서 실패한다.
([run 34076232624](https://github.com/dev-yunseong/personal-website/actions/runs/34076232624/job/101602775531))

`RequestStatisticsServiceTest.persistStatistics_ConcurrentRecording_LosesNoRequests`
가 `RequestStatisticsService` 의 옛 시그니처를 그대로 쓰고 있다.

```
error: constructor RequestStatisticsService in class RequestStatisticsService cannot be applied to given types;
  required: RequestStatisticsRepository,GeoIpLocationResolver,AsnResolver
  found:    RequestStatisticsRepository,GeoIpLocationResolver
error: incompatible types: String cannot be converted to RequestFingerprint
```

`AsnResolver` 를 생성자에 추가하고 `recordRequest` 의 User-Agent 자리를
`RequestFingerprint` 로 바꾼 변경과, 이 동시성 테스트를 추가한 변경이 서로
다른 branch 에서 진행되다가 `main` 에서 만나 생긴 semantic conflict 다.
양쪽 branch 는 각자 통과했으므로 merge 전에는 드러나지 않았다.

## Impact

`main` 의 CI 가 실패 상태이고, 테스트가 하나도 실행되지 않는다.
`main` 을 base 로 하는 모든 pull request 가 같은 컴파일 오류를 물려받는다.

## Acceptance Criteria

- [ ] `./gradlew test` 가 `main` 에서 통과한다.
- [ ] 동시성 테스트가 삭제되거나 비활성화되지 않고 그대로 검증을 유지한다.

## Constraints

`main` 의 현재 시그니처가 기준이다. production 코드는 건드리지 않는다.

## Non-goals

`AsnResolver` 나 `BotDetector` 의 동작 변경, 다른 테스트 정리.

## Validation Notes

`./gradlew test`
